blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    path("create_comment/<slug>/", views.create_comment, name="create_comment"),
    path("like_blog/", views.like_blog, name="like_blog"),
    

]

mart_main/urls.py
# martnaija_main/urls.py
"""
URL configuration for martnaija_main project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views


from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/logout/', views.custom_logout, name='admin_logout'),
    path('', include('store.urls')),
    path('auth/', include("userauths.urls")),
    path('customer/', include("customer.urls")),
    path('vendor/', include("vendor.urls")),
    path('blog/', include("blog.urls")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='userauths/password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='userauths/password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='userauths/password/password_reset_confirmation.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password/password_reset_complete.html'), name='password_reset_complete'),
    
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
# store/urls.py
from django.urls import path
from django.urls import path
from .views import markethub, markethub_category
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path("shop/", views.shop, name="shop"),
    
    path('search-products/', views.search_products, name='search_products'),
    
    path("create_category/", views.create_category, name="create_category"),
    path("category/<id>/", views.category, name="category"),
    
    path('markethub/', markethub, name='markethub'),
    path('markethub/category/<int:category_id>/', markethub_category, name='markethub_category'),
    
    path("detail/<slug>/", views.product_detail, name="product_detail"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart, name="cart"),
    path("delete_cart_item/", views.delete_cart_item, name="delete_cart_item"),
    
    path('update-cart-item/', views.update_cart_item, name='update_cart_item'),
    path('remove-cart-item/', views.remove_cart_item, name='remove_cart_item'),
    
    path("create_order/", views.create_order, name="create_order"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("coupon_apply/<order_id>/", views.coupon_apply, name="coupon_apply"),
    path("payment_status/<order_id>/", views.payment_status, name="payment_status"),
    
    path('stripe_payment/<order_id>/', views.stripe_payment, name='stripe_payment'),
    path('stripe_payment_verify/<order_id>/', views.stripe_payment_verify, name='stripe_payment_verify'),
    path('paypal_payment_verify/<order_id>/', views.paypal_payment_verify, name='paypal_payment_verify'),
    
    path('paystack_payment_verify/<order_id>/', views.paystack_payment_verify, name='paystack_payment_verify'),
    path('flutterwave_payment_callback/<order_id>/', views.flutterwave_payment_callback, name='flutterwave_payment_callback'),
    path('monnify_payment/<order_id>/', views.monnify_payment, name='monnify_payment'),
    path('monnify_payment_callback/<order_id>/', views.monnify_payment_callback, name='monnify_payment_callback'),
    path('monnify_webhook/', views.monnify_webhook, name='monnify_webhook'),
    
    path("order_tracker_page/", views.order_tracker_page, name="order_tracker_page"),
    path("order_tracker_detail/<item_id>/", views.order_tracker_detail, name="order_tracker_detail"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_conditions/", views.terms_conditions, name="terms_conditions"), 

]

userauths/urls.py
# userauths/urls.py
from django.urls import path
from userauths import views
from django.contrib.auth import views as auth_views
from userauths import views as userauths_views
from vendor import views as vendor_views
from customer import views as customer_views


app_name = "userauths"

urlpatterns = [
    path('sign-up/', userauths_views.register_view, name='sign-up'),
    path('sign-in/', userauths_views.login_view, name='sign-in'),
    path('logout/', views.logout_view, name='sign-out'),
    
    path('vendor/dashboard/', vendor_views.dashboard, name='vendor-dashboard'),
    path('customer/dashboard/', customer_views.dashboard, name='customer-dashboard'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

userauths/models.py
# userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


USER_TYPE = (    
    ("Customer", "Customer"),
    ("Vendor", "Vendor"),    
)

class User(AbstractUser):
    username = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        email_username, _ = self.email.split('@')
        if self.username == "" or self.username == None:
            self.username = email_username
        super(User, self).save(*args, **kwargs)
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='accounts/users', default='default/default-user.jpg', null=True, blank=True)
    full_name = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=255, null=True, blank=True)
    user_type = models.CharField(max_length=255, choices=USER_TYPE, null=True, blank=True, default=None)
    vendor_license = models.FileField(upload_to='accounts/vendor_licenses/', null=True, blank=True)

    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        if self.full_name == "" or self.full_name == None:
            self.full_name = self.user.full_name
        super(Profile, self).save(*args, **kwargs)

    

class ContactMessage(models.Model):
    full_name = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.full_name
    
    class Meta:
        ordering = ['-date']

userauths/forms.py
# userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox # type: ignore

from userauths.models import User

USER_TYPE = (
    ("Vendor", "Vendor"),
    ("Customer", "Customer"),
)

class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded', 'placeholder':'Full Name'}), required=True)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded', 'placeholder':'Mobile Number'}), required=True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control rounded' , 'placeholder':'Email Address'}), required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control rounded' , 'placeholder':'Password'}), required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={ 'class': 'form-control rounded' , 'placeholder':'Confirm Password'}), required=True)
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)
    vendor_license = forms.FileField(required=False, help_text='Please upload your business license or permit (PDF/Image)')
    user_type = forms.ChoiceField(choices=USER_TYPE, widget=forms.Select(attrs={"class": "form-select"}))

    class Meta:
        model = User
        fields = ['full_name', 'mobile', 'email', 'password1', 'password2', 'captcha', 'user_type', 'vendor_license']
        
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        user_type = cleaned_data.get("user_type")
        vendor_license = cleaned_data.get("vendor_license")

        if password1 != password2:
            raise forms.ValidationError("Passwords do not match.")

        if user_type == "Vendor" and not vendor_license:
            raise forms.ValidationError("Vendor license is required for vendor registration.")

        return cleaned_data
    
    
    
    def clean_vendor_license(self):
        vendor_license = self.cleaned_data.get('vendor_license')
        user_type = self.cleaned_data.get('user_type')
        
        if user_type == 'Vendor' and not vendor_license:
            raise forms.ValidationError("Vendor license is required for vendor accounts.")
        
        return vendor_license

    def save(self):
        user = User.objects.create_user(
            username=self.cleaned_data['email'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password1']
        )
        return user

class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control rounded' , 'name': "email", 'placeholder':'Email Address'}), required=False)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control rounded' , 'name': "password", 'placeholder':'Password'}), required=False)
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

    class Meta:
        model = User
        fields = ['email', 'password', 'captcha']

templates/userauths/sign-in.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}
<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Login</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle" style="margin-bottom: 400px;">
    <div class="container">
        <div class="row align-items-start justify-content-center">
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <h1 class="fw-bold mb-2">Sign In <i class="fas fa-sign-in-alt ms-2"></i></h1>
                <p class="mb-3">Welcome back, sign in to continue!</p>

                <form class="border p-3 rounded" method="POST">
                    {% csrf_token %}
                    <div class="form-group mb-4">
                        <label>Email Address *</label>
                        {{form.email}}
                    </div>

                    <div class="form-group mb-4">
                        <label>Password *</label>
                        <div class="position-relative">
                            {{ form.password }}
                            <span class="password-toggle-icon" onclick="togglePassword('id_password')">
                                <i class="fa fa-eye"></i>
                            </span>
                        </div>
                    </div>
                    

                    <div class="form-group mb-4">
                        <label>Captcha *</label>
                        {{form.captcha}}
                    </div>

                    <div class="form-group mb-4">
                        <div class="d-flex align-items-center justify-content-between">
                            
                            <div class="eltio_k2">
                                <a href="{% url 'password_reset' %}">Lost Your Password?</a>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-md full-width btn-success rounded text-light fs-md ft-medium">Login <i class="fas fa-sign-in-alt ms-1"></i></button>
                    </div>

                    <div class="mt-3">
                        <a href="{% url 'userauths:sign-up' %}">Don't have an account yet? Create account</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<style>
    .password-toggle-icon {
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
        cursor: pointer;
        color: #555;
        z-index: 2;
    }
    
    input[type="password"], input[type="text"] {
        padding-right: 40px; /* Space for the icon */
    }
</style>

<script>
    function togglePassword(fieldId) {
        const input = document.getElementById(fieldId);
        const icon = input.nextElementSibling.querySelector('i');
        if (input.type === "password") {
            input.type = "text";
            icon.classList.remove("fa-eye");
            icon.classList.add("fa-eye-slash");
        } else {
            input.type = "password";
            icon.classList.remove("fa-eye-slash");
            icon.classList.add("fa-eye");
        }
    }
</script>
    
{% endblock content %}

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<script src="https://www.google.com/recaptcha/api.js" async defer></script>



<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create Account</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-6 col-lg-6 col-md-12">
                <h1 class="fw-bold mb-2">Sign Up <i class="fas fa-user-plus ms-2"></i></h1>
                <p class="mb-3">Welcome to our store, create a free account today!</p>

                {% if form.errors %}
                    <div class="alert alert-danger">
                        <strong>Errors:</strong>
                        <ul>
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <li><strong>{% if field != '__all__' %}{{ field|title }}: {% endif %}</strong>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                            {% if form.non_field_errors %}
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}

                <form class="border p-3 rounded" method="POST" enctype="multipart/form-data" id="registration-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-md-12 mb-3">
                            <label>Full Name *</label>
                            {{ form.full_name }}
                            {% if form.full_name.errors %}
                                <div class="text-danger small">{{ form.full_name.errors }}</div>
                            {% endif %}
                        </div>

                        <div class="form-group col-md-12 mb-3">
                            <label>Email *</label>
                            {{ form.email }}
                            {% if form.email.errors %}
                                <div class="text-danger small">{{ form.email.errors }}</div>
                            {% endif %}
                        </div>

                        <div class="form-group col-md-6 mb-3">
                            <label>Mobile *</label>
                            {{ form.mobile }}
                            {% if form.mobile.errors %}
                                <div class="text-danger small">{{ form.mobile.errors }}</div>
                            {% endif %}
                        </div>

                        <div class="form-group col-md-6 mb-3">
                            <label>Password *</label>
                            <div class="position-relative">
                                {{ form.password1 }}
                                <span class="password-toggle-icon" onclick="togglePassword('id_password1')">
                                    <i class="fa fa-eye"></i>
                                </span>
                                {% if form.password1.errors %}
                                <div class="text-danger small">{{ form.password1.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        

                        <div class="form-group col-md-6 mb-3">
                            <label>Confirm Password *</label>
                            <div class="position-relative">
                                {{ form.password2 }}
                                <span class="password-toggle-icon" onclick="togglePassword('id_password2')">
                                    <i class="fa fa-eye"></i>
                                </span>
                                {% if form.password1.errors %}
                                <div class="text-danger small">{{ form.password1.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        

                        <div class="form-group col-md-6 mb-3">
                            <label>Create Account As *</label>
                            {{ form.user_type }}
                            {% if form.user_type.errors %}
                                <div class="text-danger small">{{ form.user_type.errors }}</div>
                            {% endif %}
                        </div>

                        <div class="form-group col-md-12 mb-3" id="vendor-license-container">
                            <label>Vendor License (PDF/Image) *</label><br><br>
                            {{ form.vendor_license }}
                            {% if form.vendor_license.errors %}
                                <div class="text-danger small">{{ form.vendor_license.errors }}</div>
                            {% endif %} <br>
                            <small class="text-muted">Please upload your business license or permit (Max 5MB)</small>
                        </div>

                        <div class="form-group col-md-12 mb-3">
                            <label>Captcha *</label>
                            {{ form.captcha }}
                            {% if form.captcha.errors %}
                                <div class="text-danger small">{{ form.captcha.errors }}</div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <p class="text-muted small">
                            By registering your details, you agree with our <a href="{% url 'store:terms_conditions' %}">Terms & Conditions</a>, <br>
                            and <a href="{% url 'store:privacy_policy' %}">Privacy and Cookie Policy</a>.
                        </p>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-md full-width btn-success rounded text-light">Sign Up <i class="fas fa-user-plus ms-1"></i></button>
                    </div>

                    <div class="mt-3">
                        <a href="{% url 'userauths:sign-in' %}">Already have an account? Sign In</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<style>
    .password-toggle-icon {
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
        cursor: pointer;
        color: #555;
        z-index: 2;
    }

    input[type="password"], input[type="text"] {
        padding-right: 40px; /* Ensure space for the eye icon */
    }
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const userTypeField = document.querySelector('#id_user_type');
    const vendorLicenseContainer = document.querySelector('#vendor-license-container');
    const registrationForm = document.querySelector('#registration-form');
    const passwordInput1 = document.querySelector('#id_password1');
    const passwordInput2 = document.querySelector('#id_password2');

    // Initial state
    function toggleLicenseField() {
        if (userTypeField.value === 'Vendor') {
            vendorLicenseContainer.style.display = 'block';
            // Make the license field required (HTML5 validation)
            const licenseInput = vendorLicenseContainer.querySelector('input[type="file"]');
            if (licenseInput) {
                licenseInput.required = true;
            }
        } else {
            vendorLicenseContainer.style.display = 'none';
            // Remove required attribute if not vendor
            const licenseInput = vendorLicenseContainer.querySelector('input[type="file"]');
            if (licenseInput) {
                licenseInput.required = false;
            }
        }
    }

    // Form submission validation (additional check for vendor license)
    registrationForm.addEventListener('submit', function(e) {
        if (userTypeField.value === 'Vendor') {
            const licenseInput = vendorLicenseContainer.querySelector('input[type="file"]');
            if (!licenseInput || !licenseInput.files || licenseInput.files.length === 0) {
                e.preventDefault();
                // Ensure error message is visible
                vendorLicenseContainer.style.display = 'block';
                // Create error message if it doesn't exist
                let errorDiv = vendorLicenseContainer.querySelector('.license-error');
                if (!errorDiv) {
                    errorDiv = document.createElement('div');
                    errorDiv.className = 'text-danger small license-error';
                    errorDiv.textContent = 'Vendor license is required';
                    licenseInput.parentNode.insertBefore(errorDiv, licenseInput.nextSibling);
                }
                // Scroll to the error
                vendorLicenseContainer.scrollIntoView({ behavior: 'smooth', block: 'center' });
            } else {
                // Remove error message if license is present on submit
                const errorDiv = vendorLicenseContainer.querySelector('.license-error');
                if (errorDiv) {
                    errorDiv.remove();
                }
            }
        }
    });

    // User type change handler
    userTypeField.addEventListener('change', toggleLicenseField);

    // Initialize on page load
    toggleLicenseField();
});

function togglePassword(inputId) {
    const passwordInput = document.getElementById(inputId);
    const icon = passwordInput.nextElementSibling.querySelector('i');
    if (passwordInput.type === 'password') {
        passwordInput.type = 'text';
        icon.classList.remove('fa-eye');
        icon.classList.add('fa-eye-slash');
    } else {
        passwordInput.type = 'password';
        icon.classList.remove('fa-eye-slash');
        icon.classList.add('fa-eye');
    }
}
</script>

<style>
    .password-toggle-icon {
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
        cursor: pointer;
        color: #555;
    }
</style>

{% endblock content %}